# Generated by Django 4.2.5 on 2023-10-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('themes', models.CharField(max_length=250)),
                ('rating', models.IntegerField()),
                ('description', models.TextField(max_length=3000)),
            ],
        ),
    ]
