# Generated by Django 4.2.5 on 2023-10-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_take_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.take')),
            ],
        ),
    ]
