# Generated by Django 4.2.5 on 2023-10-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_take_shots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='take',
            name='shots',
        ),
    ]
